# Generated by Django 3.2.23 on 2023-12-12 04:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='../default_post_rgq6aq', force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[1244, 1244], upload_to='images/'),
        ),
    ]
