# Generated by Django 3.2.23 on 2023-12-12 04:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='../default_user_profile_npgdiu', force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[200, 200], upload_to='images/'),
        ),
    ]
