# Generated by Django 3.2.23 on 2023-12-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='addresses',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country_culture',
            new_name='country',
        ),
    ]
